### ISSUE TITLE
Autolayout issue with iOS 4

### ISSUE THREAD

**Issue by JoshSmith** [Bernie-2016/fieldthebern-ios#87]
You can see in the screenshot below some odd issues with autolayout.

![http://imgur.com/kYuEsqO](http://i.imgur.com/kYuEsqO.jpg)

**Comment by yar1vn** [comment]
![simulator screen shot jan 13 2016 23 01 48](https://cloud.githubusercontent.com/assets/2396893/12317827/a8d0472c-ba49-11e5-999b-eb5697738a4f.png)

Tested on iPhone 4S, looks good. Is that still an issue?

**Comment by yar1vn** [comment]
![simulator screen shot jan 13 2016 23 04 08](https://cloud.githubusercontent.com/assets/2396893/12317854/f2102ec0-ba49-11e5-98a5-3db14102041a.png)

**Comment by yar1vn** [comment]
Cannot reproduce, closing for now
