### ISSUE TITLE
No autolayout / rotation support?

### ISSUE THREAD

**Issue by AaronSofaer** [Bernie-2016/fieldthebern-ios#89]
Expected: Can rotate my iPad and view the app in landscape
Expected: Can side-by-side multitask

Observed: App is locked to portrait with no multitasking. Presumably this is because we're not using the modern autolayout stack in Swift? It's very noticeable.

**Comment by yar1vn** [comment]
Currently the app does not support landscape mode. Also this is an iPhone only app and will not support multitasking on the iPad.
