### ISSUE TITLE
Add proper asset sizes and autodetect

### ISSUE THREAD

**Issue by AaronSofaer** [Bernie-2016/fieldthebern-ios#90]
We can avoid the whole 1x/2x ugliness by simply autodetecting what device someone is using and displaying for them the proper UI and asset sizes. The HIG is here:

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html

Note that we will need 3x assets on the iPhone 6+ and 6S+, and UI that actually scales properly for the Pro.

**Comment by yar1vn** [comment]
• App is supported for iPhone only and will not present properly on iPad Pro. 
• Assets are detected automatically by iOS and do contain 3x files, as well as Vector PDF files which will render to ALL screen sizes (including iPads)
