### ISSUE TITLE
Invalid characters in email field yield wrong error message

### ISSUE THREAD

**Issue by AaronSofaer** [Bernie-2016/fieldthebern-ios#92]
When the email field has an invalid character in it (such as a character with an accent), the app tells the user that the field is empty. This is not correct; the field is not empty, it is simply non-valid.

**Comment by yar1vn** [comment]
![simulator screen shot jan 13 2016 23 28 37](https://cloud.githubusercontent.com/assets/2396893/12318204/63137642-ba4d-11e5-9f94-751b7b2a1756.png)

Apparently this is already fixed.
