### ISSUE TITLE
"Bernie on the Issues" page loads very slowly the first time

### ISSUE THREAD

**Issue by AaronSofaer** [Bernie-2016/fieldthebern-ios#95]
It took a noticeable amount of time to load the "Bernie on the Issues" page when I first tried to look at it. Suspect that it's pulled at run-time? Naively, caching a copy in local state and then checking to see what's changed seems like a good idea, since this also means we'll spare peoples' data plans.

**Comment by yar1vn** [comment]
The load time is affected by your device's internet connectivity. The current API (http://feelthebern.org/ftb-json) doesn't seem to support loading changes since it doesn't take a version or a timestamp so fetching changes is not possible at the moment.
