### ISSUE TITLE
Long names don't render in Settings page

### ISSUE THREAD

**Issue by AaronSofaer** [Bernie-2016/fieldthebern-ios#97]
Expected topnav bar: Back, truncated name.
Observed topnav bar: Back, no name.

**Comment by yar1vn** [comment]
Not sure I understand the problem. Currently the Name appears in the back button label as "< John Doe". Long name will render as "< Back" instead. 
Should we put the name in the title instead and keep the back button label always "< Back"?

**Comment by AaronSofaer** [comment]
Both of your sentence clauses are violations of good HCI guidelines; inconsistent display of information in a place overloaded with functionality. :(

But hey, your call.
